apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: csi-driver-manila-controller
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: openstack-nfs-driver
      minAllowed:
        memory: {{ $.Values.resources.driver.requests.memory }}
      maxAllowed:
        memory: {{ $.Values.vpa.resourcePolicy.driver.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: openstack-nfs-nfs-driver
      minAllowed:
        memory: {{ $.Values.resources.driver.requests.memory }}
      maxAllowed:
        memory: {{ $.Values.vpa.resourcePolicy.driver.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: openstack-nfs-provisioner
      minAllowed:
        memory: {{ $.Values.resources.provisioner.requests.memory }}
      maxAllowed:
        memory: {{ $.Values.vpa.resourcePolicy.provisioner.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: openstack-nfs-snapshotter
      minAllowed:
        memory: {{ $.Values.resources.snapshotter.requests.memory }}
      maxAllowed:
        cpu: {{ $.Values.vpa.resourcePolicy.snapshotter.maxAllowed.cpu }}
        memory: {{ $.Values.vpa.resourcePolicy.snapshotter.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: openstack-nfs-resizer
      minAllowed:
        memory: {{ $.Values.resources.resizer.requests.memory }}
      maxAllowed:
        memory: {{ $.Values.vpa.resourcePolicy.resizer.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: openstack-csi-liveness-probe
      minAllowed:
        memory: {{ .Values.resources.livenessProbe.requests.memory }}
      maxAllowed:
        memory: {{ .Values.vpa.resourcePolicy.livenessProbe.maxAllowed.memory }}
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csi-driver-manila-controller
  updatePolicy:
    updateMode: Auto