replicas: 1
podAnnotations: {}

images:
  csi-driver-cinder: image-repository:image-tag
  csi-provisioner: image-repository:image-tag
  csi-attacher: image-repository:image-tag
  csi-snapshotter: image-repository:image-tag
  csi-resizer: image-repository:image-tag
  csi-liveness-probe: image-repository:image-tag
  csi-snapshot-controller: image-repository:image-tag
  csi-snapshot-validation-webhook: image-repository:image-tag

socketPath: /var/lib/csi/sockets/pluginproxy
timeout: 3m
userAgentHeaders: []

global:
  genericTokenKubeconfigSecretName: secret

resources:
  driver:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      memory: 360Mi
  provisioner:
    requests:
      cpu: 11m
      memory: 38Mi
    limits:
      memory: 400Mi
  attacher:
    requests:
      cpu: 11m
      memory: 36Mi
    limits:
      memory: 320Mi
  snapshotter:
    requests:
      cpu: 11m
      memory: 36Mi
    limits:
      memory: 220Mi
  resizer:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 220Mi
  livenessProbe:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 220Mi

vpa:
  resourcePolicy:
    driver:
      maxAllowed:
        cpu: 800m
        memory: 4G
    provisioner:
      maxAllowed:
        cpu: 800m
        memory: 4G
    attacher:
      maxAllowed:
        cpu: 500m
        memory: 4G
    snapshotter:
      maxAllowed:
        cpu: 700m
        memory: 3G
    resizer:
      maxAllowed:
        cpu: 700m
        memory: 3G
    livenessProbe:
      maxAllowed:
        cpu: 500m
        memory: 2G

csiSnapshotController:
  replicas: 1
  podAnnotations: {}
  resources:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 2.2Gi

csiSnapshotValidationWebhook:
  replica: 1
  podAnnotations: {}
  secrets:
    server: csi-snapshot-validation-server
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 200Mi

openstack:
  availabilityZones:
    - zone1
    - zone2
  shareNetworkID: shareNetworkIDValue
  shareClient: 10.180.0.0/16
  shareProtocol: NFS
  authURL: authURLValue
  region: regionValue
  domainName: domainNameValue
  projectName: projectNameValue
  userName: userNameValue
  password: userNameValue
  #applicationCredentialID: applicationCredentialIDValue
  #applicationCredentialName: applicationCredentialName
  #applicationCredentialSecret: applicationCredentialSecretValue
  #caCert: xxx
  #tlsInsecure: true

manila:
  replicas: 1
  topologyAwarenessEnabled: false
  runtimeConfig:
    enabled: false

  # Enabled Manila share protocols
  livenessProbe:
    healthPort: 11950
  nfsLivenessProbe:
    healthPort: 11951

  resources:
    driverController:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        memory: 360Mi
    provisioner:
      requests:
        cpu: 11m
        memory: 38Mi
      limits:
        memory: 400Mi
    snapshotter:
      requests:
        cpu: 11m
        memory: 36Mi
      limits:
        memory: 220Mi
    resizer:
      requests:
        cpu: 11m
        memory: 32Mi
      limits:
        memory: 220Mi
    driverNode:
      requests:
        cpu: 15m
        memory: 42Mi
      limits:
        memory: 2Gi
    nodeDriverRegistrar:
      requests:
        cpu: 11m
        memory: 32Mi
      limits:
        memory: 1Gi
    livenessProbe:
      requests:
        cpu: 11m
        memory: 32Mi
      limits:
        memory: 200Mi